### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by spali**
- optimization to save image size
- update nginx version
- get more near original nginx image

### CODE REVIEW

**Comment by cybercode** [comment]
Thanks for the pull request. I agree w/ everything except moving the daemon global to the `Dockerfile` from `nginx.conf`. I see no reason to ever run the the container w/o this argument, so it make sense to live in the config file rather than the `Dockerfile`.

**Comment by spali** [comment]
Hi
I thought too about the motivation for the deamon... but I got to the conclusion, that this allows to use the image which controls the nginx by some other process monitor or startup tool. So I thought why not just keep it so it's as much compatible to the original nginx as possible, so it could be used as a complete replacement for the original image. Even most won't even notice the difference of this detail :)
Let me know if I should drop a new pull request without this commit (or just cherry pick the commits from my repo).
I will keep it in my repo to be near the official nginx image.

**Comment by cybercode** [comment]
Merged 1903d29,  5dd1687 and 99ed328

**Comment by cybercode** [comment]
Pushed before i read your comment ;). Didn't think about the inheritance issue, maybe i'll merge 54dd409 next time i do an update...

thankx,
rick

**Pull request closed without merging**
